-- Verified organizations - 2026-03-13
-- 13 нови (7 дубликата махнати: Art Club Royana, DS Caribe, State Opera SZ, Academy of Success SZ, Sinchec, Usmivki, Elegance)
-- Категории коригирани към slug формат
-- created_by: seed user

INSERT INTO schools (id, name, category, description, phone, email, website, city, address, verified, status, neighborhood, created_by)
VALUES
  (gen_random_uuid(), 'International Children Creativity Center', 'education', 'Международен център за обучение на деца с активности като изкуство, наука, музика и езици.', '+359879403677', 'office@iccf-bg.com', 'https://iccf-bg.com', 'София', 'кв. Драгалевци', true, 'APPROVED', 'Драгалевци', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Toddlers Academy Sofia', 'education', 'Международна детска академия с модерни образователни програми и извънкласни дейности.', '+359898455375', 'info@toddlersacademy.eu', 'https://toddlersacademy.eu', 'София', 'ул. Филип Кутев', true, 'APPROVED', 'Лозенец', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'International Sports Kindergarten Smile', 'indoor-sports', 'Образователна и спортна програма за деца с активни занимания и международна среда.', NULL, NULL, 'https://www.isk-smile.com', 'София', 'кв. Бояна', true, 'APPROVED', 'Бояна', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Eco Kids Club Sofia', 'languages', 'Детски клуб с активности по английски език, музика, йога и творчески занимания.', NULL, NULL, 'https://www.seriousteachers.com/GlobalLinks/1752/Eco-Kids-Club', 'София', 'кв. Лозенец', true, 'APPROVED', 'Лозенец', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Casa dei Bambini Sofia', 'education', 'Монтесори образователен център за деца с творчески и образователни програми.', NULL, NULL, 'https://www.casadeibambini.bg', 'София', 'кв. Изток', true, 'APPROVED', 'Изток', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'British School of Sofia Activities', 'education', 'Извънкласни активности за деца – спорт, музика, шах и театър.', '+359886510510', 'office@bssofia.bg', 'https://www.bssofia.bg', 'София', 'ул. Златовръх', true, 'APPROVED', 'Лозенец', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Sofia Boys Choir', 'music-dance', 'Един от най-известните детски хорове в България с международни участия.', NULL, NULL, 'https://sofiaboyschoir.com', 'София', 'бул. Васил Левски', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Kids Club Nie Vrabchetata', 'education', 'Детски клуб за творчески и образователни дейности, включително езици и театър.', NULL, NULL, 'https://business-europe.bg/en/study-hall-in-sofia-%E2%80%93-kids%E2%80%99-club-nie%2C-vrabchetata-7561', 'София', 'ул. Оборище', true, 'APPROVED', 'Оборище', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Bulgarica Kids Dance Academy', 'music-dance', 'Академия за български фолклорни танци за деца.', NULL, NULL, 'https://bulgarica.org/en/classes/dance-academy-for-children-with-peter-iliev', 'София', 'ул. Раковски', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'State Puppet Theatre Stara Zagora Academy', 'art', 'Театрална школа за деца към Държавния куклен театър.', NULL, NULL, 'https://pierrot-bg.com', 'Стара Загора', 'ул. Генерал Гурко', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Rodina Community Center Art Groups', 'art', 'Културни и творчески групи за деца към читалище Родина.', NULL, NULL, 'https://www.rodina-bg.org', 'Стара Загора', 'бул. Цар Симеон Велики', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Children Ensemble Zagorche', 'music-dance', 'Детски фолклорен ансамбъл със сцена за танци и музика.', NULL, NULL, 'https://zagorche.wordpress.com', 'Стара Загора', 'бул. Руски', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
  (gen_random_uuid(), 'Youth Theatre Studio Scena 99', 'art', 'Младежка театрална школа с участия в спектакли и фестивали.', NULL, NULL, 'https://www.rodina-bg.org', 'Стара Загора', 'ул. Генерал Столетов', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59');
