-- Skillio: 24 нови организации — Пловдив, Варна, Бургас (без дубликати)
-- AMAkids Пловдив пропуснат — вече е в базата

INSERT INTO schools (id, name, category, description, phone, email, website, city, address, verified, status, neighborhood, created_by)
VALUES
(gen_random_uuid(), 'ЦПЛР Общински детски комплекс Пловдив', 'art', 'Общински детски комплекс с десетки школи по изкуства, спорт и наука за деца.', '+35932651417', NULL, 'https://www.odk-plovdiv.com', 'Пловдив', 'бул. Шести септември 193', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Детски учебен център Всезнайко', 'education', 'Учебен център и занималня за деца с допълнителни образователни дейности.', '+359893553477', 'info@vseznaiko.bg', 'https://www.vseznaiko.bg', 'Пловдив', 'ул. Кръстьо Пастухов 24', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Logiscool Пловдив Център', 'science', 'Школа по програмиране и дигитални умения за деца.', '+359885044822', NULL, 'https://www.logiscool.com/bg/locations/plovdiv.center', 'Пловдив', 'гр. Пловдив', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Образователен център Аргос Плюс', 'education', 'Център за допълнително обучение, езикови курсове и подготовка.', '+359887448481', 'office@argosplus.com', NULL, 'Пловдив', 'гр. Пловдив', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Езиков дом Пловдив', 'languages', 'Езиков център с курсове по английски, немски, испански и други.', '+359883933115', NULL, 'https://ezikovdom.com', 'Пловдив', 'ул. Скайлер 8', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Езиков център Школата', 'languages', 'Езиков център с курсове за деца по английски, немски и испански.', NULL, NULL, 'https://ezikod.com', 'Пловдив', 'гр. Пловдив', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Център за логопедична и психологична подкрепа С-ИВВЕНА', 'education', 'Център за детско развитие, логопедия и психологическа подкрепа.', '+359897888285', 'moyata.vselena@gmail.com', 'https://detskicentar2018.com', 'Пловдив', 'гр. Пловдив', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Езиков център Неа Германика', 'languages', 'Езиков център с обучение по европейски езици.', NULL, NULL, 'https://www.neagermanika.com', 'Пловдив', 'гр. Пловдив', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Кикбокс клуб БОИЛ Варна', 'martial-arts', 'Един от най-известните клубове по кикбокс в България.', NULL, NULL, NULL, 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Кикбокс клуб ВОКИЛ Варна', 'martial-arts', 'Клуб по кикбокс и муай тай с тренировки за деца и младежи.', NULL, NULL, NULL, 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Клуб по бойни спортове Десант Варна', 'martial-arts', 'Школа по бойни спортове и физическа подготовка.', NULL, NULL, NULL, 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Фондация Sunny Children', 'education', 'Организация за развитие и подкрепа на детски образователни дейности.', NULL, NULL, 'https://sunnykids.info', 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Академия по програмиране за деца Logiscool Варна', 'science', 'Школа по програмиране и дигитални умения.', NULL, NULL, 'https://www.logiscool.com', 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Център за ментална аритметика AMAkids Варна', 'education', 'Център за интелектуално развитие и ментална аритметика.', NULL, NULL, 'https://amakids.com', 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Фолклорен ансамбъл Булгари Варна', 'music-dance', 'Ансамбъл и школа по български народни танци.', NULL, NULL, NULL, 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Детски танцов клуб Булгари', 'music-dance', 'Танцова школа за деца с обучение по народни танци.', NULL, NULL, NULL, 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Образователен център Аргос Плюс Варна', 'education', 'Център за обучение и подготовка на ученици.', NULL, NULL, NULL, 'Варна', 'гр. Варна', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Фолклорна школа Зеленика', 'music-dance', 'Детска школа по български народни танци.', '+359877053540', NULL, NULL, 'Бургас', 'ул. Апостол войвода 15', true, 'APPROVED', 'Меден рудник', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Международен младежки център Бургас', 'education', 'Център с множество образователни и културни дейности за деца.', NULL, 'office@yicburgas.bg', 'https://yicburgas.bg', 'Бургас', 'ул. Апостол войвода 15', true, 'APPROVED', 'Меден рудник', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Център за детско развитие Моята Вселена', 'education', 'Център за ранно детско развитие и образователни дейности.', NULL, NULL, NULL, 'Бургас', 'гр. Бургас', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Център за детско развитие SmartyKids Бургас', 'education', 'Школа за ментална аритметика и развитие на логическо мислене.', NULL, NULL, 'https://smarty-kids.bg', 'Бургас', 'гр. Бургас', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Академия по музика Калинa Спасова', 'music-dance', 'Музикални занимания за малки деца.', '+359882700527', NULL, NULL, 'Бургас', 'ул. Славянска 77', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Академия за дигитални умения Logiscool Бургас', 'science', 'Обучение по програмиране и технологии за деца.', NULL, NULL, 'https://www.logiscool.com', 'Бургас', 'гр. Бургас', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59'),
(gen_random_uuid(), 'Детска школа по народни танци Бургас', 'music-dance', 'Школа по български народни танци за деца.', NULL, NULL, NULL, 'Бургас', 'гр. Бургас', true, 'APPROVED', 'Център', '4a212536-a4ea-4b97-ac67-d38ef23ebc59');
